# Generated by Django 4.2.2 on 2023-06-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
