# Generated by Django 4.2.2 on 2023-06-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nam',
            new_name='name',
        ),
    ]
